TRANSLATE = {
    "deepseek-reasoner": "assistant_DeepSeek-R1",
    "deepseek-chat": "assistant_DeepSeek-V3",
    "doubao-seed-1-6-thinking-250715": "assistant_豆包1.6 Thinking",
    "doubao-seed-1-6-250615": "assistant_豆包1.6",
    "gemini-2.5-pro": "assistant_Gemini 2.5 Pro",
    "gemini-2.5-flash": "assistant_Gemini 2.5 Flash",
    "gemini-2.5-flash-lite": "assistant_Gemini 2.5 Flash-Lite",
    "DeepSeek-R1": "deepseek-reasoner",
    "DeepSeek-V3": "deepseek-chat",
    "Doubao-Seed-1.6-thinking": "doubao-seed-1-6-thinking-250715",
    "Doubao-Seed-1.6": "doubao-seed-1-6-250615",
    "Gemini 2.5 Pro": "gemini-2.5-pro",
    "Gemini 2.5 Flash": "gemini-2.5-flash",
    "Gemini 2.5 Flash-Lite": "gemini-2.5-flash-lite",
    "auto": "自动",
    "enabled": "开",
    "disabled": "关闭",
    "自动": "auto",
    "开": "enabled",
    "关闭": "disabled",
}
