TRANSLATE = {
    "deepseek-chat": "assistant_DeepSeek-V3.2",
    "doubao-seed-1-8-251228": "assistant_豆包1.8",
    "gemini-3-flash-preview": "assistant_Gemini 3 Flash",
    "gemini-2.5-flash": "assistant_Gemini 2.5 Flash",
    "gemini-2.5-flash-lite": "assistant_Gemini 2.5 Flash-Lite",
    "mistral-large-2512": "assistant_Mistral Large 3",
    "glm-4.7-flash": "assistant_GLM-4.7-Flash",
    "DeepSeek-V3.2": "deepseek-chat",
    "Doubao-Seed-1.8": "doubao-seed-1-8-251228",
    "Gemini 3 Flash": "gemini-3-flash-preview",
    "Gemini 2.5 Flash": "gemini-2.5-flash",
    "Gemini 2.5 Flash-Lite": "gemini-2.5-flash-lite",
    "Mistral Large 3": "mistral-large-2512",
    "GLM-4.7-Flash": "glm-4.7-flash",
    "minimal": "无",
    "low": "低",
    "medium": "中",
    "high": "高",
    "无": "minimal",
    "低": "low",
    "中": "medium",
    "高": "high",
}
